/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'programInterest' : IDL.Text,
  'phone' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : IDL.Text,
  'quote' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'submitAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'programInterest' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : IDL.Text,
    'quote' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'submitAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };