/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'serviceType' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'phone' : string,
}
export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'message' : string,
  'programInterest' : string,
  'phone' : string,
}
export interface Testimonial {
  'id' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : string,
  'quote' : string,
  'rating' : bigint,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addTestimonial' : ActorMethod<[string, string, string, bigint], bigint>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'submitAppointment' : ActorMethod<
    [string, string, string, string, string, string],
    boolean
  >,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];